### ISSUE TITLE
[EPIC] Prplmesh testing in boardfarm

### ISSUE THREAD

**Issue by abelog** [prplfoundation/prplMesh#1074]
## Description

To resolve point of #893 we have to create infrastructure in boardfarm to represent prplMesh specific devices, entities and tests.
Classes, their relations between each other may be taken from #1032.

## Exit criteria

- boardfarm infrastructure (dummy docker representation, prpMesh entities representation, real device representation) is ready.
- Flows, from `test_flows.py` are ported to boardfarm and are working on dockerized "dummy" prplMesh with same results.
- Flows, from `test_flows.py` are ported to boardfarm and are working on real HW (RAX40).
- Boardfarm tests are included to prplMesh repo, as `test_flows.py`.

### Included tasks

- [x] #1069 Deliver boardfarm along with prplMesh 
- [x] #1080  Boardfarm test template 
- [x] #1071 Port `test_initial_ap_config` to boardfarm for dockerized device
- [x] #1072 Port `test_initial_ap_config` to boardfarm for prplWRT device
- [ ] #1381 Integrate boardfarm in gitlab-ci.
- [ ] #1122 Port all flow tests to boardfarm
- [ ] #1125 Implement VirtualAP for prplWrt device
- [ ] #1124 Add interface to query status

In addition, we'll take this occasion to fix a pending issue:
- [ ] #822 tests are not isolated

### Acceptance criteria
- Boardfarm infrastructure is able to handle all tests of `test_flows.py` (required devices, class fields and methods are created and tested)
- All tests of `test_flows.py` are ported to boardfarm
- Tests can be run again real RAX40 and dockerized "dummy" mode
