### ISSUE TITLE
[TASK] Autoconfig phase 2 - encryption support

### ISSUE THREAD

**Issue by tomereli** [prplfoundation/prplMesh#126]
## Description

Encryption support for autoconfig WSC M1+M2 in prplMesh.
The goal is to add the encryption parameters for M1 and M2 WSC messages, add encryption support to the framework and use it to encrypt the attributes of the encrypted settings in the M2 message which contains the configuration for the radio agent.
On receive, the radio agent will authenticate the message using the authenticator attribute in the M2 message, and then decrypt the encrypted settings.

### Encryption

- [x] Add Diffie-Hellman Key exchange
- [x] Add function for generating nonce
- [x] Add function for sha256
- [x] Add function for AES encryption
- [x] Add function for sha256/AES HMAC
- [x] Compute authentication and key wrap keys according to WSC spec
- [x] Perform HMAC on encrypted settings to generate authenticator and key_wrap_auth
- [x] Apply the above to M2 frame
- [x] Authenticate and decrypt the data in the agent to verify the above

### TLVF support for encryption

The M2 message includes multiple strings, which are implemented in the TLVF using variable-length lists. Support for multiple variable-length lists has recently been added, but there is no support class members or variable-length lists class members.
This is required for the encrypted settings in the M2 TLV since it contains multiple attributes and a length field, so it has to be a TLV class (although not a real TLV).
PR #91 (WIP) adds support for dynamic length list of classes for this purpose and actually is working. It was considered a valid workaround since it was thought that the encrypted settings are the last member of the WSC M2 TLV, but apparently, it is not - since the last attribute is the validator attribute.

The solution has to be adding support for class members - which should involves adding `memmov` support like done in #115 and #116 (the reason we can't use variable length list of classes of size 1 is that it will include the length field which is not part of the M2 frame).

**TODO - open a new task for this**

- [x] Add support for class members

## Exit criteria

- [x] Controller and remote agent pass m1/m2 and get to operational
- [x] Agent decryptes the encrypted settings and prints them. Compare they match what was set in the controller. Remove the prints afterwards
- [x] Autoconfig packets captured in Wireshark and are valid
- [x] Compare to Arris autoconfig Wireshark capture

## Detailed description
Section 5.7.1 in [beerocks_1.4 architecture.pdf](https://github.com/prplfoundation/prplMesh/blob/master/documentation/BeeRocks_v1_4_Architecture.pdf)

- **Problem statement** - Passing easymesh certification
- **Possible solutions** - this was chosen as first step for not breaking existing functionality. We could have replaced join with auto config altogether.
- **Components affected** - controller/agent/framework/common
- **Build considerations** - None
- **Dependencies** - ZMQ for intra node communication
