### ISSUE TITLE
[TASK] WSC Flow phase 1 - support for non-Intel agents

### ISSUE THREAD

**Issue by tomereli** [prplfoundation/prplMesh#134]
## Description

Currently, prplMesh controller supports Intel agents only since it still relies on the vendor specific TLV which contain the slave join data.
In order to support none-Intel agents such as the CTT agent in the certificaiton testbed, this has to be changed - on receiving WSC AP-Autoconfiguration message from a radio agent, a new node shall be added to the controller DB with all of the radio agent's information as received in the AP Radio Basic capabilities and WSC M1 TLVs.
The controller will then send a WSC AP-Autoconfiguration response message containing M2 TLV and the flow will continue per specification.

## Subtasks

- [ ] Design review - 1.5 SPs
- [ ] Add support in database for none-Intel agents - 3 SPs
  - [ ] Update DB Node structure to support none-Intel agents including all M1 info (manufacturer, serial number, etc.)
  - [ ] Update CLI `dump_node_info` command to show also the new params from the M1/M2 messages
  - [ ] Update CLI `bml_conn_map` command to show the manufacturer string next to each radio agent
- [ ] Add support in controller for none-Intel agents
  - [ ] Simulate none-intel Agent using beerocks agent which does not add the VS TLV - 1 SP
  - [ ] Map data used by the controller and agent in slave join flow which is not available as part of M2 and M2 - 1 SP
  - [ ] Remove slave join response VS TLV from WSC Autoconfig M2 message - all data should be available in WSC M2 - 2 SP
  - [ ] Remove slave join request VS TLV from WSC Autoconfig M1 message - all data should be available in WSC M1 - 2 SP

## Exit criteria
- DR including test plan
- Pass CI
- Pass code review
- Simulate none-Intel Agent, get to operational, show `bml_conn_map` and `dump_node_info` contain all the M1 and M2 information and that the controller and agent are operational

## Detailed description

- **Problem statement** - Currently prplMesh supports only Intel agents due to vendor specific information which is sent in a vendor specific TLV as part of autoconfig flow. This will not be the case in the certification since the agent will not be Intel.
- **Possible solutions** - Add support for none Intel agent - only solution.
- **Components affected** - controller/agent
- **Build considerations** - None
- **Dependencies** - None

**Comment by tomereli** [comment]
@arnout can you update this task? We want to close this milestone since we are ready to start testing and move to the new milestone added by @vegyraupe - https://github.com/prplfoundation/prplMesh/milestone/4

**Comment by arnout** [comment]
This was done in various pull requests - too many to list here.
