### ISSUE TITLE
[EPIC] Initial Northbound API implementation

### ISSUE THREAD

**Issue by ghost** [prplfoundation/prplMesh#1394]
## Description

For M3, we've agreed to implement a high level API for prplMesh based on the Data Elements specification, but with support for non-WiFi agents as well.
This API should be accessible from the system bus (e.g. ubus) by using the BAAPI library.

## Tasks

- [ ] #1400 Add the baapi library to our repo and build it
- [ ] Analyse the Data Elements specification and create a gap analysis regarding the work to be done in prplMesh to support DE
- [ ] prplMesh refactoring to support DE
- [ ] create initial Northbound API based on DE, using baapi
- [ ] create tests for Northbound API using some tool that uses the system bus to query data
