### ISSUE TITLE
[EPIC] Essential refactoring tasks

### ISSUE THREAD

**Issue by ghost** [prplfoundation/prplMesh#1396]
## Description

Several refactoring tasks that were agreed on for M3.

## Exit criteria

- [ ] All refactoring tasks are done

## Tasks

- [ ] Replace all vendor specific messages with standard messages + create non-standard messages for prplmesh extensions to the spec
- [ ] [Endless autoconfig search in product](https://github.com/prplfoundation/prplMesh/issues/554) #554 
- [ ] process manager
    - Basic functionality only (fork and pass file descriptors, drop permissions for children, no monitoring)
- [ ] controller database refactoring
- [ ] [unified agent](https://github.com/prplfoundation/prplMesh/issues/1082) #1082 
- [ ] Replace ZMQ with Vitaly's bus
- [ ] Add mocks for easy testing and verification of connected components to Vitaly's bus
- [ ] bml cli: Use HL API for topology database
- [ ] bwl refactoring (clean up inheritance graph + better define APIs+ unittest)
- [ ] Monitor thread, stats and database
- [ ] [Socket implementation rework](https://github.com/prplfoundation/prplMesh/issues/546) #546
