### ISSUE TITLE
[EPIC] Easymesh R2 preparation

### ISSUE THREAD

**Issue by ghost** [prplfoundation/prplMesh#1398]
## Description

In order to prepare for going through the Easymesh R2 certification effort in M4, we need to prepare in M3.

## Tasks

- [ ] Easymesh R2 analysis & estimation
- [ ] #1405 Initial Easymesh R2 testbed assembly and configuration
- [ ] #1152 Align DCS implementation with Easymesh R2 specification
