### ISSUE TITLE
[EPIC] Platform support

### ISSUE THREAD

**Issue by ghost** [prplfoundation/prplMesh#1399]
## Description

We need to support various different platforms for M3.

## Tasks

- [ ] BWL nl80211: #1480, #1481, #1482 
- [ ] GL.inet support
- [ ] Turris Omnia support
- [ ] Axepoint support
- [ ] RDK-B support
    - [ ] [Add RDK-B build job to CI](https://github.com/prplfoundation/prplMesh/issues/1393) #1393 
    - [ ] Run boardfarm tests on an RDK-B platform
