### ISSUE TITLE
[FEATURE] Band steering

### ISSUE THREAD

**Issue by arnout** [prplfoundation/prplMesh#298]
Implement band steering (i.e. force a client to switch from 5GHz to 2.4GHz or vice versa) end to end.

As a first step, implement manual band steering through BML command, and only using Legacy steering.

- [x] #294 Dummy BWL support for band steering
- [x] #293 Band steering test
- [x] #295 Client association with EasyMesh messages
- [x] #296 Agent steering request
- [x] #327 Agent steering request is only handled by 1 slave
- [x] #323 Convert BTM disassociation timer to units of 1TU
- [x] #297 Controller client steering task
- [x] #328 Remove vendor-specific steering message
- [ ] #315 Store operating classes in database
- [x] #316 Controller uses Client Access Control messages
- [x] #317 Implement Client Access Control in agent
- [x] #432 Change access control disassociation timer value

To complete the band steering, all options have to be covered.

- [ ] Implement BTM steering in agent.
- [ ] Implement BTM in dummy BWL.
- [ ] Implement BTM in hostapd
- [ ] Implement BTM response in dummy BWL
- [ ] Implement BTM response in hostapd
- [ ] Handle BTM response in controller
- [ ] Implement Client Access Control in hostapd

**Comment by arnout** [comment]
This issue should be split in the part that will be done for the demo milestone, and the part that is required for certification.

**Comment by arnout** [comment]
Closing this since the milestone is closed.
