### ISSUE TITLE
Topology discovery full support

### ISSUE THREAD

**Issue by arnout** [prplfoundation/prplMesh#300]
## Description

For certification, it is sufficient to only support part of topology discovery (cfr. #120, #186). For a fully operational controller, however, it is needed to fully support topology discovery at least in the controller. It is also required in the agent if IEEE 1905.1 compliance is desired.

- [x] #120 Topology discovery -  Controller certification
- [x] #186 5.3.1 Supported discovery
- [x] #525 Construct topology response message
- [x] #830 Make a design for complete topology discovery support
- [x] #1160 per-interface Topology Discovery message
- [x] #1425 Extend topology database to store neighbor's interface and MAC address 
- [x] #1428 Use neighbor's interface info in Topology Response 
- [ ] #701 Add Device Bridging Capability TLV to Topology Response message 
- [ ] #925 Detect topology changes on the network 

## Exit criteria

- Topology agent (framework/discovery_agent/) is built
- Topology agent is started by prplmesh_utils.sh
- Topology agent sends a topology notification every 60 seconds
- Topology agent listens for topology query and constructs topology response (#525)

### Problem statement

Both the agent and the controller, when operating independently, must perform the topology discovery functions. Therefore, it is not simply possible to implement this functionality in one of them.

Both the agent and the controller need to know some of the topology information. Mainly the controller needs it to discover stations connecting and disconnecting.

### Possible solutions

1. The functionality is provided by a library in common or framework and linked with both controller and agent. If a device has both agent and controller, the agent signals its presence to the controller and the controller disables its topology functionality.
2. An additional component takes care of the topology discovery. This component is always running (much like the ieee1905_transport component), in agent, controller, and agent+controller mode.

The second option is conceptually cleaner so that one is chosen.

### Components affected

A topology discovery agent already exists in framework/discovery_agent, but it is currently not built and probably broken. So that has to be revived.

The discovery is responsible for sending out notifications regularly. It will also be responsible for most of the rest of the IEEE1905.1 functionality, though that doesn't need to be implemented for EasyMesh certification.

Topology information is needed by agent and controller as well. The topology discovery agent will manage the protocol messages (e.g. sending out regular topology discovery messages and responding with topology query). The other components will keep a local topology database and listen to the relevant CMDUs (e.g. responses to the topology queries sent out by the topology discovery agent) to update that database.

Agent and controller may also emit topology related messages autonomously. For example, the agent emits a topology notification message when a station connects or disconnects. That functionality will stay in the agent.

For now, the topology discovery doesn't need to actually construct a topology database. That will be needed for sending 1905.1 neighbour information, but we don't need that at this time.

**Comment by tomereli** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Discovery agent full support](https://trello.com/c/6sFxLvDl/18-discovery-agent-full-support)
