### ISSUE TITLE
4.3.1 Supported Services Discovery

### ISSUE THREAD

**Issue by arnout** [prplfoundation/prplMesh#341]
The prplMesh agent on Turris Omnia with OpenWrt needs to pass the certification test case 4.3.1 as defined by the Wi-Fi CERTIFIED EasyMesh (tm) Test Plan.

- [ ] #300 Topology discovery full support
- [x] #339 Pass flow 4.3.1 Ethernet backhaul test in testbed
- [ ] #340 Pass flow 4.3.1 Wireless backhaul test in testbed
