### ISSUE TITLE
4.2.1 Multi-AP Ethernet Onboarding and Initialization 

### ISSUE THREAD

**Issue by arnout** [prplfoundation/prplMesh#345]
The prplMesh agent on Turris Omnia with OpenWrt needs to pass the certification test case 4.2.1 as defined by the Wi-Fi CERTIFIED EasyMesh (tm) Test Plan.

- [x] #336 Support wfa_ca in agent
- [x] #346 AP configuration on Turris Omnia / RAX40 OpenWrt
- [x] #343 Test flow for 4.2.1 Multi-AP Ethernet Onboarding and Initialization
- [x] #344 Pass flow 4.2.1 test in testbed

**Comment by tomereli** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Non-Intel controller support](https://trello.com/c/7kJiE6W0/17-non-intel-controller-support)

**Comment by tomereli** [comment]
Currently failing since channel switch is using bandwidth=0 instead of bandwidth=20 which causes the channel switch to fail in the hostapd and therefore we don't send the operating channel report.

**Comment by tomereli** [comment]
With #889 , we pass all stages of 4.2.1 except for channel selection in the 5G radio.
The reason for this is that in RAX40, DFS is enabled by default, but the channel preferences sent by the UCC application does not take DFS channels into account, which results with no change needed in prplmesh since the DFS channel we're on is not restricted.

As a matter of fact, the UCC identifies our RAX40 device as supporting 2.4G and 5GL only, so it doesn't include the 5G high channels such as 157.
Regardless, the UCC does not mark the DFS channels as non-operable in any configuration (see MAP-4.2-MAUT-ChanSel.txt).

The outcome of this is simple - if ACS selected DFS channel or 5GH channel (e.g. 157), the channel selection request sent from the controller will not include these channels in the non-operable channel list since this is hard coded in the UCC code.
The result is that prplMesh will decide not to perform channel switch since the current channel is not restricted. This is the correct behavior so nothing is expected to change in this PR.

The certification test code should be modified so that these channels are marked as non-operable so that when the UCC means to switch to channel 36, the switch will happen since all channels except for channel 36 are non-operable.

A temporary solution is to disable DFS in certification mode, implemented in https://git.prpl.dev/prplmesh/iwlwav/-/merge_requests/7, but this does not guarantee that the test will pass since the high channels might be automatically selected during ACS.

A mail was sent to the WiFi alliance certification support regarding this - support case # 00129476

**Comment by arnout** [comment]
#899 does not actually close this issue, since #343 is still open.

**Comment by tomereli** [comment]
> #899 does not actually close this issue, since #343 is still open.

Weird, why did mergfy decide to close this issue? Cause I linked it to the PR?

**Comment by arnout** [comment]
> > #899 does not actually close this issue, since #343 is still open.
> 
> Weird, why did mergfy decide to close this issue? Cause I linked it to the PR?

Yes, that is exactly what linking an issue to a PR means: when the PR is merged, close the issue.

Also, if you mention an issue in the PR description (not a comment) then it will be linked automatically.

If you just want to refer to an issue, simply mention it in a comment. A backlink will be created.

**Comment by tomereli** [comment]
Actually #343 is not needed since it is already covered by channel selection test and autoconfig, so marking this as Done
