### ISSUE TITLE
4.2.3 Multi-AP Wi-Fi Onboarding and Initialization test 2

### ISSUE THREAD

**Issue by arnout** [prplfoundation/prplMesh#348]
The prplMesh agent on Turris Omnia with OpenWrt needs to pass the certification test case 4.2.3 as defined by the Wi-Fi CERTIFIED EasyMesh (tm) Test Plan.

- [ ] #337 Revive Multi-AP PBC procedure
- [ ] #342 Implement START_WPS_REGISTRATION_INTERFACE
- [ ] #347 Pass flow 4.2.3 test in testbed

**Comment by arnout** [comment]
Relies on #336 #346 #343 to be done as well.
