### ISSUE TITLE
4.3.2 Client association and disassociation

### ISSUE THREAD

**Issue by arnout** [prplfoundation/prplMesh#353]
The prplMesh agent on Turris Omnia with OpenWrt needs to pass the certification test case 4.3.2 as defined by the Wi-Fi CERTIFIED EasyMesh (tm) Test Plan.

- [x] #421 Client Association Event
- [x] #525 Properly construct topology response message
- [x] #351 Test flow for 4.3.2 Client association and disassociation
- [x] #352 Pass flow 4.3.2 test in testbed

**Comment by ghost** [comment]
Everything needed to pass 4.3.2 has been completed (and tests are passing), so closing this issue.
