### ISSUE TITLE
4.4.3 AP configuration BSS Tear Down

### ISSUE THREAD

**Issue by arnout** [prplfoundation/prplMesh#362]
The prplMesh agent on Turris Omnia with OpenWrt needs to pass the certification test case 4.4.3 as defined by the Wi-Fi CERTIFIED EasyMesh (tm) Test Plan.

- [ ] #361 Test flow for 4.4.3 AP configuration BSS Tear Down
- [x] #791 Update VAP list after VAP config
- [ ] #360 Pass flow 4.4.3 test in testbed
