### ISSUE TITLE
4.5.2 Channel Selection Request Message

### ISSUE THREAD

**Issue by arnout** [prplfoundation/prplMesh#368]
The prplMesh agent on Turris Omnia with OpenWrt needs to pass the certification test case 4.5.2 as defined by the Wi-Fi CERTIFIED EasyMesh (tm) Test Plan.

- [x] #366 Channel selection for nl80211
- [x] #725 Perform channel selection
- [x] #369 Implement Operating Channel Report for nl80211
- [ ] #367 Pass flow 4.5.2 test in testbed

**Comment by ghost** [comment]
See #1360 and #1364
