### ISSUE TITLE
4.7.1,2,3 Link Metric Collection

### ISSUE THREAD

**Issue by arnout** [prplfoundation/prplMesh#391]
The prplMesh agent on Turris Omnia with OpenWrt needs to pass the certification test cases 4.7.1 through 4.7.3 as defined by the Wi-Fi CERTIFIED EasyMesh (tm) Test Plan.

Since all these tests are very similar, they are collected into a single milestone entry.

- [x] #390 Link metric collection for Ethernet links
- [x] #792 Link metric collection for WiFi links
- [ ] #381 Pass flow 4.7.1 test in testbed
- [ ] #382 Pass flow 4.7.2 test in testbed
- [x] #383 Pass flow 4.7.3 test in testbed

**Comment by arnout** [comment]
Moving to M2 since 4.7.1 and 4.7.2 are wireless backhaul.

This issue really should be split in two, but it's not worth the bother.
