### ISSUE TITLE
4.7.9 Beacon Metrics Query and Response

### ISSUE THREAD

**Issue by arnout** [prplfoundation/prplMesh#399]
The prplMesh agent on Turris Omnia with OpenWrt needs to pass the certification test case 4.7.9 as defined by the Wi-Fi CERTIFIED EasyMesh (tm) Test Plan.

- [x] #972 Implement Beacon Metrics Query and Response messages
- [ ] #398 Test flow for 4.7.9
- [x] #389 Pass flow 4.7.9 test in testbed
