### ISSUE TITLE
4.8.1,2,3,5 Client Steering

### ISSUE THREAD

**Issue by arnout** [prplfoundation/prplMesh#405]
The prplMesh agent on Turris Omnia with OpenWrt needs to pass the certification test case 4.8.1, 4.8.2, 4.8.3 and 4.8.5 as defined by the Wi-Fi CERTIFIED EasyMesh (tm) Test Plan.

- [x] #429 Correct information in BTMSteeringReport message
- [x] #400 Pass flow 4.8.1 test in testbed
- [x] #401 Pass flow 4.8.2 test in testbed
- [x] #986 Handle Client Steering Opportunity
- [x] #402 Pass flow 4.8.3 test in testbed
- [x] #404 Pass flow 4.8.5 test in testbed

**Comment by rmelotte** [comment]
Here is the current status:
- MAP-4.8.2_ETH_FH24G
Fails [with the Qualcomm controller](https://gitlab.com/prpl-foundation/prplMesh/-/jobs/454093091), but passes [with the Marvell controller](https://gitlab.com/prpl-foundation/prplMesh/-/jobs/454165724).

There is an issue to track the failures with some of the certified controllers here: https://github.com/prplfoundation/prplMesh/issues/921

- MAP-4.8.3_ETH_FH5GL
Job here: https://gitlab.com/prpl-foundation/prplMesh/-/jobs/454253682
It currently fails with:
```
2020-02-28 19:05:49.099 - INFO - MSG:  No 1905 Ack message found 
```

- 4.8.4 and 4.8.5 fail because they use the Mediatek and Qualcomm controllers respectively, with which prplMesh currently fails on the onboarding
