### ISSUE TITLE
4.10.1-6 Data Passing

### ISSUE THREAD

**Issue by arnout** [prplfoundation/prplMesh#417]
The prplMesh agent on Turris Omnia with OpenWrt needs to pass the certification test cases 4.10.1-6 as defined by the Wi-Fi CERTIFIED EasyMesh (tm) Test Plan.

- [ ] #411 Pass flow 4.10.1 test in testbed
- [ ] #412 Pass flow 4.10.2 test in testbed
- [ ] #413 Pass flow 4.10.3 test in testbed
- [ ] #414 Pass flow 4.10.4 test in testbed
- [ ] #415 Pass flow 4.10.5 test in testbed
- [ ] #416 Pass flow 4.10.6 test in testbed
