### ISSUE TITLE
4.11.1 Multi-AP Control Messaging Reliability

### ISSUE THREAD

**Issue by arnout** [prplfoundation/prplMesh#422]
The prplMesh agent on Turris Omnia with OpenWrt needs to pass the certification test case 4.11.1 as defined by the Wi-Fi CERTIFIED EasyMesh (tm) Test Plan.

- [x] #421 Client Association Event
- [ ] #273 Architecture for handling ACKs and retransmissions (optional, can be hacked)
- [x] #769 Reliable multicast
- [x] #418 Pass flow 4.11.1 test in testbed

**Comment by tomereli** [comment]
Reference POC branch - https://github.com/prplfoundation/prplMesh/pull/1264/files

**Comment by ghost** [comment]
Done for now. #273 will be dealt with later on.
