### ISSUE TITLE
[TASK] Move slave radio enumeration to bpl

### ISSUE THREAD

**Issue by arnout** [prplfoundation/prplMesh#574]
## Description

Move the configuration of which slaves to start (wlan0, wlan1, wlan2, ...) to BPL instead of getting it from a configuration file.

- non hostap_iface configuration is moved to #803
- backhaul configuration is moved to #803

## Exit criteria

- bpl_cfg has functions to get slave config;
- hostap_iface is removed from the config file.
- when this task is completed, OpenWrt must be updated as well as described in #787

## Detailed description

Semantically, the configuration of which radios to use in prplMesh and which interface to use for backhaul should be part of the platform (i.e. retrieved from UCI), not in the internal configuration file. CFR. #542 

This is made more difficult because the slaves and the backhaul manager are started before a connection is made with the platform manager. Therefore, first, the code flow has to be refactored to start the platform manager first, wait for it to become online, and only then start the slaves and backhaul manager.

### sub-tasks ###
phase 1:
- [x] add hostap_iface param to the /etc/config/prplmesh
- [x] provide infrastructure to get the hostap_iface from the prplmesh config for a given radio/slave
- [x] provide API to get all hostap-interfaces (slave_agent_main requires to know all the configured hostap-interfaces of the configured slaves before starting the slaves)
- [x] propagate the read hostap_iface information read to the son_slave, platform_manger and backhaul_manager
- [x] remove the hostap_iface from the beerocks_config
- [x] add a similar PR to prplmeshOpenWrt
phase 2:
- [x] move all radio/agent configuration from beerocks_agent.conf to the prplmesh config file
phase 3:
- [x] move backhaul configuration from beerocks_agent.conf to the prplmesh config file

**Comment by arnout** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Move slave and backhaul configuration to bpl](https://trello.com/c/LVU2RyOG/37-move-slave-and-backhaul-configuration-to-bpl)

**Comment by arnout** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [move sta_iface from beerocks_agent.conf to bpl](https://trello.com/c/UEflUZjg/49-move-staiface-from-beerocksagentconf-to-bpl)

**Comment by adam1985d** [comment]
the following internal JIRA issue is related to the issue:
WLANRTSYS-19633
