### ISSUE TITLE
[TASK] Move platform manager to a separate process

### ISSUE THREAD

**Issue by tomereli** [prplfoundation/prplMesh#575]
## Description

Access to the platform DB and operations should only be done by a single entity (process) since it reduces the attack surface by limiting the number of processes that need access to privileged platform operations. For example, a bug in the agent will not give access to bridge control assuming correct access rights are set for each process.

In addition, all controller and agent's configuration should be moved to the platform DB (#574, #568) in order to remove target dependencies from prplMesh build system.

However, the platform manager is currently a thread in the main agent, and moving all the configuration parameters to the platform DB can't be done since the controller (and local agents) need to know the configuration on init.

In order to meet the above - The platform manager thread needs to be converted to a process, and renamed to "platform service". It should be the first process that is started so that every component can request the platform DB, trigger platform operations, and register to platform notifications.

Eventually, the platform service should (if built without `BPL_UDS` - similar to `BTL_UDS`) communicate via the local bus, similarly to the transport service, but with a `platform.` prefix.

It should expose API to get the current platform DB, and publish notifications to all subcscribers whenever there are DB updates. It should also verify the identity of any process with which it interacts (**TBD decide how exactly**).

**Subtasks**
- [ ] Map out the controller and agent configuration options that should move to the platform DB
- [ ] Replicate the controller and agent configuration in the platform DB, for example:
`uci show prplmesh.config.controller` shows the controller config
`uci show prplmesh.config.agent` shows the agent config
Debug options can stay in configuration files.
- [ ] Add platform service process which starts at init (copy of the platform manager thread) but still does not interact with prplmesh. The platform service should have a CMAKE option if to build in UDS or Local bus modes. At this point only UDS is used.
- [ ] Add UDS socket listener and register to the platform service at controller and agent init.
- [ ] Use the platform service instead of the platform manager thread
- [ ] Delete the platform manager thread

In a new PR, add local bus mode, in which the platform manager connects to the local bus and defines its own set of messages which are passed on the bus. The platform service subscribes only to `platform.tx.*` messages, which are sent from any component in prplMesh, and replies with `platform.rx.*`. Define the messages, and the steps to accomplish that.

## Exit criteria

- All operating related configuration (non debug) is moved to platform DB
- The platform service builds in UDS mode and starts first
- The agent and controller request the DB status from the platform service on boot
- On DB updates, the platform service broadcasts a notification (in UDS mode - to all the open sockets) for any DB update or platform status change.

**Comment by tomereli** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [platform manager as a separate process](https://trello.com/c/XIkUc9O0/38-platform-manager-as-a-separate-process)

**Comment by arnout** [comment]
Some comments/observations:

> However, the platform manager is currently a thread in the main agent, and moving all the configuration parameters to the platform DB can't be done since the controller (and local agents) need to know the configuration on init.

For the agent, this is a largely independent issue (#574). For the controller it is related since the controller doesn't really have access to the platform DB at the moment, it has to go through the "platform config" section of the slave join.


> In order to meet the above - The platform manager thread needs to be converted to a process, and renamed to "platform service".

Why does it have to be renamed?

> It should be the first process that is started so that every component can request the platform DB, trigger platform operations, and register to platform notifications.

The bus should still be first :-)

Actually, ideally there shouldn't be a strict ordering. Instead there should be a way for the bus interface to block until a set of topics is available (i.e. at least one listener is registered). Or alternatively the local_bus should queue messages until a listener is registered (and all processes should start with pinging the services they need). But that's a completely separate issue, of course.

> Eventually, the platform service should (if built without BPL_UDS - similar to BTL_UDS) communicate via the local bus, similarly to the transport service, but with a platform. prefix.

I would actually want to get rid of BTL_UDS entirely, and replace it with a purely-UDS-based local_bus implementation. That will also make it easier to connect the slaves directly to the bus.


> It should expose API to get the current platform DB, and publish notifications to all subcscribers whenever there are DB updates.

I think a nice approach would be to implement #568 so that the config DB is a simple string->string mapping. Then we can make a message that contains a db update (= list of string->string mappings with the updated entries), and keep a cache in each process (cfr. the current slaveConfig struct).

> It should also verify the identity of any process with which it interacts (TBD decide how exactly).

This is silly. That's exactly what the system bus is supposed to do (I agree that ubus doesn't do it, but adding another bus that solves the issue for part of the system is not going to change it). If this is a requirement, we should either use the system bus or a bus that has this feature (e.g. dbus).

> Subtasks
> 
> - Map out the controller and agent configuration options that should move to the platform DB
> - Replicate the controller and agent configuration in the platform DB, for example:
>   `uci show prplmesh.config.controller` shows the controller config
>   `uci show prplmesh.config.agent` shows the agent config

I think the `config` part is not needed. What else is there than config? If it is kept, I think it should be reversed, i.e. `prplmesh.agent.config`.

> - Debug options can stay in configuration files.
> - Add platform service process which starts at init (copy of the platform manager thread) but still does not interact with prplmesh. The platform service should have a CMAKE option if to build in UDS or Local bus modes. At this point only UDS is used.

At this point we should also decide how to deal with the slaves: connect straight to the bus, or let the backhaul manager forward the messages like is done for the 1905.1 messages, or keep listening on UDS in the platform manager.

> - Add UDS socket listener and register to the platform service at controller and agent init.
> - Use the platform service instead of the platform manager thread
> - Delete the platform manager thread

**Comment by tomereli** [comment]
> > In order to meet the above - The platform manager thread needs to be converted to a process, and renamed to "platform service".
> 
> Why does it have to be renamed?

It doesn't have to, but it would be nice since it would align to services terminology - transport service, platform service, management service (which is a different topic).

> 
> > It should be the first process that is started so that every component can request the platform DB, trigger platform operations, and register to platform notifications.
> 
> The bus should still be first :-)
> 

Yep, forgot about that :) Although it depends on the bus - with ZMQ there is nothing preventing the subscribers and publishers to start before the broker. Its just that the messages will be dropped until the broker starts.

> Actually, ideally there shouldn't be a strict ordering. Instead there should be a way for the bus interface to block until a set of topics is available (i.e. at least one listener is registered). Or alternatively the local_bus should queue messages until a listener is registered (and all processes should start with pinging the services they need). But that's a completely separate issue, of course.
> 
> > Eventually, the platform service should (if built without BPL_UDS - similar to BTL_UDS) communicate via the local bus, similarly to the transport service, but with a platform. prefix.
> 
> I would actually want to get rid of BTL_UDS entirely, and replace it with a purely-UDS-based local_bus implementation. That will also make it easier to connect the slaves directly to the bus.
> 

That's a very good point and definitely the direction we should go with - we anyway want to replace ZMQ. But this deserves a separate issue - if you have a proposition for a UDS based MSGLIB implementation can you create an issue for that?

> > It should expose API to get the current platform DB, and publish notifications to all subcscribers whenever there are DB updates.
> 
> I think a nice approach would be to implement #568 so that the config DB is a simple string->string mapping. Then we can make a message that contains a db update (= list of string->string mappings with the updated entries), and keep a cache in each process (cfr. the current slaveConfig struct).
> 

Yes, #568 should be implemented as part of or as a dependency for this issue.


> At this point we should also decide how to deal with the slaves: connect straight to the bus, or let the backhaul manager forward the messages like is done for the 1905.1 messages, or keep listening on UDS in the platform manager.
> 

That's something to discuss in the arch meeting.

**Comment by morantr** [comment]
There is absolutely no need for the platform manager to be BTL or bus-based. This is needed only on threads that need to communicate with thread on other platforms, which is not the case here.
