### ISSUE TITLE
[TASK][Channel scan] use AP Radio Basic Capabilities TLV  to validate channel pool

### ISSUE THREAD

**Issue by kantera800** [prplfoundation/prplMesh#686]
currently channel pool validated by static table supported_channels_array[] of channels in db::set_dcs_channel_pool()

This is  incorrect  since radio setup could vary with different country configuration.

We need permanent and generic prplMesh solution:
- [x] refactor read_supported_channels to use get_radio_info #1024  (PR #1043)
- [x] update Radio Basic Capabilities TLV using the new supported_channels (PR  #1065)
- [x] [bug] missing channels when using nl80211_client::get_radio_info #1046 (PR #1053)
- [x]  use supported_channels from AP Radio Basic Capabilities data for channel scan pool validation in db instead of static table (PR #1093)

poc PR - do not merge #941

**Comment by arnout** [comment]
> create new structure in node.h std::vector<beerocks_message::sWifiChannel> phy_supported_channels
> save GET_HW_FEATURES report during in slave_join to DB.

This is exactly what ap_wlan_hal->read_supported_channels() does, no? So what exactly needs to be done here?

**Comment by kantera800** [comment]
> > create new structure in node.h std::vector<beerocks_message::sWifiChannel> phy_supported_channels
> > save GET_HW_FEATURES report during in slave_join to DB.
> 
> This is exactly what ap_wlan_hal->read_supported_channels() does, no? So what exactly needs to be done here?

in case we are currently on a static channel and we want to scan , read_supported_channels() returns just this channel.
also ,  i heard that read_supported_channels() is not going to be used soon.
we need to store in the db latest channel list that fw supports for the dcs feature.
