### ISSUE TITLE
[TASK] Pass 4.6.1 test - AP capability report

### ISSUE THREAD

**Issue by CoralMalachi** [prplfoundation/prplMesh#707]
## Description

According to the Wi-Fi CERTIFIED EasyMesh™ Test Plan v1.0, test 4.6.1, which is the AP capability report test, the MAUT is triggered by the CTT controller with an AP Capability Query message, and the MAUT should replay with AP Capability Report message.

According to Multi-AP-Spesification, when a Multi-AP Agent receives an AP Capability Query message, it shall respond within one second with an AP Capability Report message which includes :

- one **AP Capability TLV**
- one **AP Radio Basic Capabilities TLV** for each AP radio.
- If an AP radio supports 802.11 High Throughput capability, a Multi-AP Agent shall include an **AP HT Capabilities TLV** for that radio.
- If an AP radio supports 802.11 Very High Throughput capability, a Multi-AP Agent shall include an **AP VHT Capabilities TLV** for that radio.
- If an AP radio supports 802.11 High-Efficiency capability, a Multi-AP Agent shall include an **AP HE Capabilities TLV** for that radio.

## Exit criteria

This task can be split into the following subtasks:
- [x] move the handle of AP Capability Query message from `son_slave_thread` to the `backhaul_manager_thread` (#692)
- [x] Send  an AP Capability TLV as part of the AP Capability Report message CMDU (#692)
- [x] Send an AP Radio Basic Capabilities TLV for each AP radio (#692)
- [x] Fetch the AP HT/VHT Capabilities from the Wi-Fi driver via the Netlink socket (#1127)
- [x] Send the AP Capabilities TLVs according to the info we got from the driver (#1148).
- [ ] Fetch the AP HE Capabilities from the Wi-Fi driver via the Netlink socket and include them into AP HE Capabilities TLV (#1162)

Note: last subtask cannot be tested with RAX40. It is not required to pass test 4.6.1.

**Comment by ghost** [comment]
Seems this was closed prematurely (depends on #1162 )
