### ISSUE TITLE
[EPIC] Test flow refactoring

### ISSUE THREAD

**Issue by ghost** [prplfoundation/prplMesh#738]
# Description

Currently, all flows being tested are in a single shell script, with calls to docker to invoke certain commands on emulated agents.
The plan is to make this more modular by rewriting the test flows in python:

* Make it easier to add new tests
* Put each test in its own file
* Make it extensible so we can run the same tests on actual hardware as well (by abstracting away the target platform)
* Allow test hierarchies (controller/agent/algorithm test separation, for instance)

# Exit criteria

- [x] #726 Move test flows to top level directory
- [x] #894 Create python test framework
- [x] Move existing tests to python test framework
- [x] #896 Refactor test_flows.py
- [x] #919 Investigate whether we can use board farm
- [x] #1140 Document test_flows.

Some shortcoming of current tests should be addressed implicitly:

- [x] #821 check_error should be initialized

**Comment by arnout** [comment]
Moved #822 to #1074

**Comment by ghost** [comment]
All subtasks of this epic are done, so closing it :-)
