### ISSUE TITLE
[EPIC] Single certification testbed configuration

### ISSUE THREAD

**Issue by ghost** [prplfoundation/prplMesh#848]
## Description

At the moment we have only 2 testbeds, but we might have more in the future. 

To keep the testbeds as close as possible to each other, we would like to keep most of the configuration the same. 
In theory, only the MAC addresses of the devices need to be different, all the rest of the configuration could be the same. 
This epic is meant to keep track of what needs to be done for the testbed configurations to share a single configuration. 

The current configuration can be found in a group of repositories here: https://gitlab.com/prpl-foundation/easymesh_cert .

## Exit criteria

- [ ] The testbed configuration is complete with all the devices and setup done that we need for effective testing
- [ ] the testbed configuration in use is thoroughly documented on the wiki\
- [ ] The testbed configuration is the same everywhere 

## Detailed description

- [x] #745 Share device IPs
- [x] #840 Master PC bringup
- [x] #846 bring up marvell STA
- [x] #842 Bring up UCC
- [x] #844 Bring up ASUS sniffer
- [x] #845 Bring up mediatek AP
- [x] #847 Bring up broadcom 
- [x] #841 run all tests
- [x] #843 Bringup prplmesh DUT (RAX40)

**Comment by ghost** [comment]
@tomereli I think this is now 100% done, right? Can we close this epic or is there something else you want to do in this scope?

**Comment by tomereli** [comment]
We can close this one
