### ISSUE TITLE
[EPIC] Wireless backhaul support

### ISSUE THREAD

**Issue by ghost** [prplfoundation/prplMesh#861]
## Description

This epic collects all the work needed for Wireless backhaul support.
To be clear, this work does NOT include the work needed for backhaul steering -- that task is separate.

Only the wired backhaul link is supported currently. The job to be done in this epic consists in modifying the agent so it can use the wireless backhaul link when the wired link is not available. Wired backhaul link must be always preferred over the wireless because it's supposed to be faster and more reliable. Also, during agent start up there are no link metrics available to help making such a decision. There can be up to two wireless backhaul links available (2.5 Ghz and 5 Ghz) and agent should be able to use both of them. Agent should continuously monitor the backhaul link being used and switch to another one if it goes down. Agent should also switch if while using a wireless link then the wired link goes up. Some sort of hysteresis should be considered in this case to avoid switching too often. It is the responsibility of the controller to gather link metrics and steer agents to use the best link available, so in any case an agent must collect link metrics for this purpose.

## Exit criteria

- [ ] All certification tests relating to wireless backhaul pass
- [ ] Adequate unit/integration tests have been written related to wireless backhaul management
- [ ] Those tests are passing

## Detailed description

- [ ] #862 Create a detailed design for wireless backhaul support
- [ ] #863 Create unit/integration tests related to wireless backhaul support
- [x] #864 Add bAP (backhaul AP) support to prplMesh
- [ ] #865 Verify the backhaul station is up when prplMesh starts
- [ ] #866 Dynamic switching between wired and wireless (autonomously, based on link status)
          This task does not include run time switching between different backhaul links based on received backhaul steering messages (will be done separately)

A link to the detailed design should be added to this description after #862 has been completed.
