### ISSUE TITLE
[TASK] Create unit/integration tests related to wireless backhaul support

### ISSUE THREAD

**Issue by ghost** [prplfoundation/prplMesh#863]
## Description

After the detailed design described in #862 is done, tests should be created to verify that the design is implemented correctly and working.

## Exit criteria

- [ ] Adequate unit and/or integration tests exist for wireless backhaul support
- [ ] The tests correctly indicate the current state of the implementation

## Detailed description

See #861 

The tests are necessary to have full confidence in our wireless backhaul support and to close #861. They can be written before or after the actual implementation has been written; it is left up to the implementer.

At a minimum, these tests should:
- [ ] test that wireless backhaul STA status is correctly determined at prplmesh startup (#865)
- [ ] test that wireless backhaul link will be used when available, and required (#864 )
- [ ] test that the backhaul link will switch dynamically if current link goes down (#866)
- [ ] test that the backhaul link used will not switch too often in case the wired link status goes up and down very quickly (i.e. that there is a minimum time between switching attempts) (#866)
