### ISSUE TITLE
[TASK] Detect topology changes on the network

### ISSUE THREAD

**Issue by morantr** [prplfoundation/prplMesh#925]
based on #906 summary
## Description

Implement a mechanism which detects on the controller side that an Agents Radio/BSSID went down.

## Problems
In the past, we used to have a TCP/IP socket between the Controller and the Agent.
When a radio went down, the son_slave perform reset and closed the socket to the controller.
When that happened, the socket on the controller side was closed too, and the controller removed the node of the son_slave from the database.

Nowadays, we have a BUS infrastructure that replaces the TCP/IP socket.  This means that if the son_slave perform reset,
No socket is closed and the controller doesn’t aware that and Agent radio is down.

## IEEE 1905.1 Topology Discovery flow brief
The topology discovery protocol uses the multicast discovery procedure, the unicast topology
query/response procedure, and the relayed multicast topology notification procedure to enable a
1905.1 management entity to discover the network topology. These procedures make use of the following
messages:
- Topology discovery message (neighbor multicast)
- IEEE 802.1 bridge discovery message (neighbor multicast)
- Topology query message (unicast)
- Topology response message (unicast)
- Topology notification message (relayed multicast)

Once all interfaces are ready and the Agent establishes a backhaul link then within 1 s, a 1905.1 management entity shall transmit a topology discovery message every 60 seconds.
The 1905.1 management entity shall transmit a topology discovery message on neighbor multicast.

Each 1905.1 management entity (Agent), shall subscribe and listen to the Discovery Topology messages and add all the neighbors it knows to neighbor device TLV on Topology Response message.

If Agent2 disconnects from a different Agent1, it will not get Discovery Topology message for more than 60 seconds and report it on Associated Clients TLV and 1905.1 neighbor device TLV that is in the Topology response message.

### Phase 1 - Update Agent node on Controller database
This phase is required for detecting radio on the Agent that went down.
 - [x] Send Topology Query message on the Controller upon receiving auto-config **M1 or Search** message (?). 
 - [x] Send Topology Query message on the Controller upon receiving Topology Notification Message with zero Client Association Event TLV. 
 - [x] Add missing radio interfaces as dummy information to device information TLV which is sent on Topology Response message on the Agent (backhaul manager).
 - [x] If a son_slave socket of a specific radio interface is not connected, the Agent (backhaul manager) shall not add it to the device information TLV which is sent on Topology Response message it sends.
- [x] When son_slave socket disconnects or connects, the Agent should send a topology notification with no TLVs.
- [x] Create a handler for Topology Response message on the Controller that identifies a radio interface that is no longer active and removes it from the database.

### Phase 2 - Update Topology network map on the Controller
This phase is required for detecting Agent that went down - a platform that was turned off for example.
- [x] Create a container that holds 1905.1 neighbor devices on the Agent (backhaul manager).
- [x] Add 1905.1 neighbor device TLV to Topology Response message which is sent by the Agent (backhaul manager).
- [x] Subscribe to the Discovery Topology message on the Agent (backhaul manager) and fill each neighbor to the newly added neighbor container.
- [x] Remove the Discovery Topology subscription and handling from the controller.
Currently, the controller adds the node of the AL MAC which sent the message to its DB.
This should be moved to the Topology Response message handler and be based on the 1905.1 neighbors list TLV.
- [x] The Agent (backhaul manager) shall check periodically that it continues to receive Topology Discovery message from a specific neighbor every 60 seconds, and remove it from the database it gets a timeout.
- [x] ~When the Agent (backhaul manager) removes a neighbor from the neighbors' container, it shall send a Topology Notification with Client Association Event TLV mentioning that the client is disconnected.~
When the Agent (backhaul manager) adds or removes a neighbor to/from the neighbors' container, it shall send a Topology Notification without TLVs.

### Phase 3 - Code removal & Refactoring
Remove proprietary old code (not based on the standard) that detects and handles Agent/radio down. This code is replaced by the code that will be implemented in phases 1&2.
- [ ] Remove deprecated Controller/Agent PING mechanism between the son_master and the son_slaves which is not relevant anymore since it is not based on MultiAP standard (and also it is very ugly).
- [ ]  Remove Controllers son_slave node “last_seen” field from the database and monitoring of it on network_health_check task since it is replaced by a standard-based solution.
- [ ] Move all topology code to a separate class.

**Comment by arnout** [comment]
It's a pity that you didn't keep the full description of all the TLVs involved from #906 - that was really useful. (nitpick)

The Topology Discovery flow brief that you added here is also super-useful. Kudos!

---
> IEEE 802.1 bridge discovery message

We will probably need to implement that (eventually) to be really 1905.1 compliant (@mariomaz to confirm), but AFAICS it serves no useful purpose because in practice no consumer device implements LLDP.

---
> Create a container that holds 1905.1 neighbor devices on the Agent (backhaul manager).

This is a little bit more complicated than it sounds here, because you also need to keep track of the interfaces involved.

---
> The Agent (backhaul manager) shall check periodically that it continues to receive Topology Discovery message from a specific neighbor every 60 seconds, and remove it from the database it gets a timeout.

I realize now there's an additional issue here. Since the links are (theoretically) not reliable, the 60s timeout may not be appropriate. In practice the links (even wireless) *are* pretty reliable so maybe we don't need to care. So maybe we should create an issue for M3 or M4 to make this reliable by sending an explicit topology query (and repeat it a couple of times) before removing the node. Or maybe this aspect should be added to #273.

---
> When the Agent (backhaul manager) removes a neighbor from the neighbors' container, it shall send a Topology Notification with Client Association Event TLV mentioning that the client is disconnected.

This is wrong. Client Association is when a client disconnects, which is more or less independent of the neighbor container stuff. If the client is a backhaul STA, then indeed the client association event TLV should be added, but that's just the generic client association code we already have.

In addition, it's not just when it's removed but also when it's added.

So I think this should be:

When the Agent (backhaul manager) adds or removes a neighbor to/from the neighbors' container, it shall send a Topology Notification without TLVs.

Also, for efficiency, we may want to wait about 1s before actually sending the notification. Else, on startup, you'll get a flood of notifications while neighbours are added one by one. But that's something we can evaluate later (separate issue, and maybe not even needed).

---
> Send Topology Query message on the Controller upon receiving auto-config M1 or Search message (?).

We definitely need to send Topology Query when receiving a Topology Notification without TLVs. We also need to send a topology query whenever a new node is added to the database for whatever reason (as a neighbour of an existing one, or due to M1 or search or for whatever other reason).

---
> Add missing radio interfaces ad dummy information to device information TLV which is sent on Topology Response message on the Agent (backhaul manager)

What do you mean with "dummy information"?

I also still don't know what we need to include in the Device Infmration TLV interface list for wireless: radio UIDs, VAP BSSIDs, or nothing? Nothing -> same reasoning as in 1905.1a powerdown: radios and VAPs are already included in AP Operational BSS TLV so don't need to be in interface list.

I think we should check what the certified agents send.

---
> If a son_slave socket of a specific radio interface is not connected, the Agent (backhaul manager) shall not add it to the device information TLV which is sent on Topology Response message it sends.

Also if the son_slave socket disconnects or connects, the agent should send a topology notification.

---
> Remove Controllers son_slave node “last_seen” field from the database and monitoring of it on network_health_check task since it is replaced by a standard-based solution.

Should that task also be removed entirely, or does it still have a function?

---
Additional subtask: update the architecture documentation with this.

---
For the controller modifications, would it make sense to prioritise #524 which would simplify them? Or maybe vice versa, #524 becomes simpler after removing the deprecated stuff?

**Comment by morantr** [comment]
> It's a pity that you didn't keep the full description of all the TLVs involved from #906 - that was really useful. (nitpick)
> 
> The Topology Discovery flow brief that you added here is also super-useful. Kudos!
> 
> > IEEE 802.1 bridge discovery message
> 
> We will probably need to implement that (eventually) to be really 1905.1 compliant (@mariomaz to confirm), but AFAICS it serves no useful purpose because in practice no consumer device implements LLDP.
> 
> > Create a container that holds 1905.1 neighbor devices on the Agent (backhaul manager).
> 
> This is a little bit more complicated than it sounds here, because you also need to keep track of the interfaces involved.
> 
> > The Agent (backhaul manager) shall check periodically that it continues to receive Topology Discovery message from a specific neighbor every 60 seconds, and remove it from the database it gets a timeout.
> 
> I realize now there's an additional issue here. Since the links are (theoretically) not reliable, the 60s timeout may not be appropriate. In practice the links (even wireless) _are_ pretty reliable so maybe we don't need to care. So maybe we should create an issue for M3 or M4 to make this reliable by sending an explicit topology query (and repeat it a couple of times) before removing the node. Or maybe this aspect should be added to #273.
> 
> > When the Agent (backhaul manager) removes a neighbor from the neighbors' container, it shall send a Topology Notification with Client Association Event TLV mentioning that the client is disconnected.
> 
> This is wrong. Client Association is when a client disconnects, which is more or less independent of the neighbor container stuff. If the client is a backhaul STA, then indeed the client association event TLV should be added, but that's just the generic client association code we already have.
> 
> In addition, it's not just when it's removed but also when it's added.
> 
> So I think this should be:
> 
> When the Agent (backhaul manager) adds or removes a neighbor to/from the neighbors' container, it shall send a Topology Notification without TLVs.

Changed the description.
> 
> Also, for efficiency, we may want to wait about 1s before actually sending the notification. Else, on startup, you'll get a flood of notifications while neighbours are added one by one. But that's something we can evaluate later (separate issue, and maybe not even needed).
> 
> > Send Topology Query message on the Controller upon receiving auto-config M1 or Search message (?).
> 
> We definitely need to send Topology Query when receiving a Topology Notification without TLVs. We also need to send a topology query whenever a new node is added to the database for whatever reason (as a neighbour of an existing one, or due to M1 or search or for whatever other reason).
> 
> > Add missing radio interfaces ad dummy information to device information TLV which is sent on Topology Response message on the Agent (backhaul manager)
> 
> What do you mean with "dummy information"?
> 
> I also still don't know what we need to include in the Device Infmration TLV interface list for wireless: radio UIDs, VAP BSSIDs, or nothing? Nothing -> same reasoning as in 1905.1a powerdown: radios and VAPs are already included in AP Operational BSS TLV so don't need to be in interface list.
> 
> I think we should check what the certified agents send.

Currently, we don't have an API that gives us the information to fill this TLV. I will have to fill it with dummy values. 
> 
> > If a son_slave socket of a specific radio interface is not connected, the Agent (backhaul manager) shall not add it to the device information TLV which is sent on Topology Response message it sends.
> 
> Also if the son_slave socket disconnects or connects, the agent should send a topology notification.

Added subtask.
> 
> > Remove Controllers son_slave node “last_seen” field from the database and monitoring of it on network_health_check task since it is replaced by a standard-based solution.
> 
> Should that task also be removed entirely, or does it still have a function?

Not sure, basically it is also responsible to remove client nodes from the database that are suspicious to be disconnected. 
> 
> Additional subtask: update the architecture documentation with this.
> 
> For the controller modifications, would it make sense to prioritise #524 which would simplify them? Or maybe vice versa, #524 becomes simpler after removing the deprecated stuff?

Nah, they do not influence each other.

**Comment by morantr** [comment]
Added one more subtask: 
"Create a handler for the Topology Response message on the Controller."

**Comment by morantr** [comment]
Added:
"Send Topology Query message on the Controller upon receiving Topology Notification Message with zero Client Association Event TLV. "

**Comment by ghost** [comment]
See #830 and #300

**Comment by arnout** [comment]
Discussion during the F2C meeting:
- network map is going to be used externally, how often does it really need updates? Once every 5 seconds sounds like frequently enough.
- According to the specification, however, the agent has to send a topology notification within 1s whenever anything changes. So we should definitely stick to that.
- Also, for some algorithms, realtime information may really be needed. So sending the topology query immediately when a topology notification is received is probably best. Maybe serve the first one, but then no new query within e.g. 5s.
- We should probably have some other mechanism to limit the number of messages from an agent to prevent DoS attacks.
